; Sample of a correct ‘client.ini’ file :

# [observability]
# enabled=true
# collectorHost="http://localhost:4357"
# environnement="dev"
# level="trace"

[network]
websocket_url="ws://192.168.49.2:7040"
