@tool
class_name VolcanicGeothermalActiveVolcanoTerrain
## Terrain module for the **volcanic_geothermal-active_volcano** biome.
##
## Active lava flows, vents — caldera features with a lava pool at the
## centre.  The caldera geometry is generated by [VolcanicCaldera] and
## placed by [VolcanicSpawner]; this module provides the terrain-mesh
## depression constants used by PlanetChunk during mesh generation.
## Category: volcanic.  Layer group: individual (polygon).

# ── Constants ──────────────────────────────────────────────────────

## Biome type string as defined in the QGIS catalogue.
const BIOME_TYPE := "volcanic_geothermal-active_volcano"
## Biome index in the catalogue (0-based).
const BIOME_INDEX := 26
## Category tag for grouping.
const CATEGORY := "volcanic"

# ── Terrain depression constants ──────────────────────────────────

## Radius of the terrain depression around the caldera (metres).
## Should be at least as large as VolcanicCaldera.OUTER_RADIUS so the
## depression encompasses the full caldera structure.
const DEPRESSION_RADIUS_M := 50.0
## Depth of the depression at the caldera centre (metres).
## Matches VolcanicCaldera.CALDERA_DEPTH.
const DEPRESSION_DEPTH_M := 25.0

# ── Visual identity ───────────────────────────────────────────────

## Dark basalt base colour.
const COL_BASALT_DARK := Color(0.10, 0.07, 0.06)
## Medium basalt.
const COL_BASALT := Color(0.18, 0.12, 0.10)
## Scoria — reddish volcanic rubble.
const COL_SCORIA := Color(0.30, 0.15, 0.10)
## Caldera rim — slightly lighter basalt.
const COL_RIM := Color(0.22, 0.14, 0.11)
## Inner wall hot colour near lava.
const COL_INNER_HOT := Color(0.40, 0.12, 0.05)
## Lava edge glow.
const COL_LAVA_EDGE := Color(0.95, 0.30, 0.05)


# ── Detection helpers ──────────────────────────────────────────────

## Returns true if the biome definition is an active volcano.
static func is_active_volcano_biome(bd: BiomeDefinition) -> bool:
	return bd != null and bd.biome_type == BIOME_TYPE


## Check whether a zone should produce an active volcano depression.
static func matches_zone(bd: BiomeDefinition) -> bool:
	return is_active_volcano_biome(bd)
