@tool
class_name VolcanicGeothermalFumaroleTerrain
## Self-contained constants and helpers for fumarole terrain depressions.
##
## Fumaroles are volcanic gas emanations escaping from fissures — localized
## features that create a crater-like depression in the terrain with a shallow
## bowl shape.  The vent itself is generated by [VolcanicGeothermalFumaroleVent]
## and placed by [VolcanicGeothermalFumaroleSpawner]; this module provides the
## terrain-mesh depression constants used by PlanetChunk during mesh generation.
## All constants are local to this module — independent of other biomes.

# ── Terrain depression constants ──────────────────────────────────

## Radius of the terrain depression around the fumarole vent (metres).
## Should be slightly larger than VolcanicGeothermalFumaroleVent.DEBRIS_RING_RADIUS so the
## depression encompasses the full debris field.
const DEPRESSION_RADIUS_M := 15.0
## Depth of the depression at the vent centre (metres).
const DEPRESSION_DEPTH_M := 8.0

## Biome type string as defined in the QGIS catalogue.
const BIOME_TYPE := "volcanic_geothermal-fumarole"
## Biome index in the catalogue (0-based).
const BIOME_INDEX := 30
## Category tag.
const CATEGORY := "volcanic"

# ── Visual identity ───────────────────────────────────────────────

## Dark basalt base colour of the vent area.
const COL_BASALT := Color(0.15, 0.12, 0.10)
## Sulfur mineral crust — bright yellow-ochre staining.
const COL_SULFUR := Color(0.72, 0.68, 0.22)
## Rim highlight — light sulfur yellow.
const COL_RIM := Color(0.85, 0.80, 0.35)
## Inner throat glow — hot orange.
const COL_THROAT := Color(0.95, 0.45, 0.12)


# ── Detection helpers ──────────────────────────────────────────────

## Returns true if the biome definition is a fumarole.
static func is_fumarole_biome(bd: BiomeDefinition) -> bool:
	return bd != null and bd.biome_type == BIOME_TYPE


## Check whether a zone should produce a fumarole depression.
static func matches_zone(bd: BiomeDefinition) -> bool:
	return is_fumarole_biome(bd)
