version: '3.8'

services:
  neo4j:
    image: neo4j:5.15-community
    container_name: persistence-neo4j
    restart: unless-stopped
    ports:
      - "7474:7474"   # Interface web Neo4j Browser
      - "7687:7687"
    environment:
      NEO4J_AUTH: none
      NEO4J_PLUGINS: '["apoc"]'
      NEO4J_dbms_memory_heap_initial__size: 512m
      NEO4J_dbms_memory_heap_max__size: 1G
      NEO4J_dbms_memory_pagecache_size: 512m
      NEO4J_dbms_security_procedures_unrestricted: apoc.*
      NEO4J_dbms_security_procedures_allowlist: apoc.*
      NEO4J_dbms_default__listen__address: 0.0.0.0
      NEO4J_dbms_connector_bolt_listen__address: 0.0.0.0:7687
      NEO4J_dbms_connector_http_listen__address: 0.0.0.0:7474

    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins

      # Optionnel: scripts d'initialisation
      #- ./init-scripts:/docker-entrypoint-initdb.d

    networks:
      - persistence-network

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins:

networks:
  persistence-network:
    driver: bridge
