"""Asset Browser catalog generation.

Single responsibility: turn material tags into the catalog tree that Blender
reads from blender_assets.cats.txt.

Deliberately free of any bpy import, so it can be tested with a plain Python
interpreter instead of requiring a Blender runtime.
"""

from __future__ import annotations

import uuid
from pathlib import Path

CATALOG_FILE_NAME = "blender_assets.cats.txt"
CATALOG_FILE_VERSION = 1

# Catalogs are derived from this tag category, so the Asset Browser tree
# mirrors the vocabulary instead of inventing a second taxonomy.
CATALOG_TAG_CATEGORY = "family"
FALLBACK_CATALOG = "uncategorized"

# Fixed namespace: catalog UUIDs must stay identical across rebuilds, otherwise
# Blender treats every regenerated asset as newly uncategorised.
_CATALOG_NAMESPACE = uuid.UUID("6f3b7c2a-1d4e-5a8b-9c0d-2e1f3a4b5c6d")


def catalog_uuid(catalog_path: str) -> str:
    """Return a stable UUID for a catalog path."""
    return str(uuid.uuid5(_CATALOG_NAMESPACE, catalog_path))


def catalog_path_for(tags: list[str], family_tags: set[str]) -> str:
    """Pick the catalog a material belongs to.

    The first tag belonging to the family category wins. Materials without one
    land in a visible fallback catalog rather than disappearing from the tree.
    """
    for tag in tags:
        if tag in family_tags:
            return tag
    return FALLBACK_CATALOG


def family_tags_from_vocabulary(vocabulary: dict) -> set[str]:
    """Extract the family category from a parsed tags.json."""
    return set(vocabulary["categories"][CATALOG_TAG_CATEGORY])


def render_catalog_file(catalog_paths: set[str]) -> str:
    """Render the blender_assets.cats.txt content for a set of catalogs."""
    lines = [
        f"VERSION {CATALOG_FILE_VERSION}",
        "",
        "# Generated by tools/build_asset_library.py. Do not edit by hand.",
        "",
    ]
    for path in sorted(catalog_paths):
        # Format is uuid:catalog/path:display name
        lines.append(f"{catalog_uuid(path)}:{path}:{path.replace('_', ' ').title()}")
    return "\n".join(lines) + "\n"


def write_catalog_file(directory: Path, catalog_paths: set[str]) -> Path:
    """Write the catalog file next to the generated .blend and return its path."""
    target = directory / CATALOG_FILE_NAME
    target.write_text(render_catalog_file(catalog_paths), encoding="utf-8")
    return target
