name: "Godot gut test"
on:
  push:
    branches:
      - '*'
    tags:
       - '*'
  # Runs test suite when a PR is opened or synchronyzed
  pull_request:
  # Runs test suite every night
  schedule:
    - cron:  '0 0 * * *'
  
jobs:
  execute-gut:
    name: Run GUT tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # disabled because server meshing in rewrite mode :D
      #- name: Docker test
      #  uses: ceceppa/godot-gut-ci@main
      #  with:
      #    godot_version: 4.4.1
